# == Rational ==
# To enable development work in the private repo, but at the same time open our
# work in the main branch to the public.
#
# == Description ==
# Whenever a push to main happens in actions-remaker-dev, this workflow syncs
# the main branch to the public actions-remaker repo.
#
# == Requirements ==
# A personal access token (ACTIONS_REMAKER_TOKEN) with Contents and Workflows
# read/write permission on BugSwarm/actions-remaker must be stored as a secret
# in this repository.


name: Sync

on:
  push:
    branches:
      - main

jobs:
  priv_to_pub:
    name: Sync private repo to public repo
    if: github.repository == 'BugSwarm/actions-remaker-dev'
    runs-on: ubuntu-latest

    steps:
      - name: Clone source repo (bare)
        run: git clone --bare https://x-access-token:${{ secrets.ACTIONS_REMAKER_TOKEN }}@github.com/BugSwarm/actions-remaker-dev.git repo

      - name: Push main branch to public repo
        run: |
          cd repo
          git push https://x-access-token:${{ secrets.ACTIONS_REMAKER_TOKEN }}@github.com/BugSwarm/actions-remaker.git refs/heads/main:refs/heads/main
